apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/feature-gate: TechPreviewNoUpgrade
  labels:
    app: webhooks
  name: platform-operators-rukpak-webhooks
  namespace: openshift-platform-operators
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhooks
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        include.release.openshift.io/self-managed-high-availability: "true"
        release.openshift.io/feature-gate: TechPreviewNoUpgrade
      labels:
        app: webhooks
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: webhooks
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /webhooks
        image: quay.io/operator-framework/rukpak:main
        imagePullPolicy: IfNotPresent
        name: webhooks
        ports:
        - containerPort: 8080
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      serviceAccountName: platform-operators-rukpak-webhooks-admin
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: platform-operators-rukpak-webhook-tls
